# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Hashblu Blog
email: somnath@hashblu.com
description: > # this means to ignore newlines until "baseurl:"
  Hashblu is a London based startup aimed at making self service and 
  self care for Enterprises & SMES …Simple, Secure, Easy and measurable in ‘Blink times’
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://hashblu.com" # the base hostname & protocol for your site
twitter_username: hashblu
#github_username:  jekyll

# Build settings
markdown: kramdown

comments: true