---
title: Hashblu
email: somnath@hashblu.com
author: Hashblu
author_github: Hashblu
description: |
  Hashblu blog
baseurl: "/"
url: http://hashblu.github.io/hashblu-blog
paginate: 12
github:
  user: Hashblu
  repository: hashblu.github.io
  url: http://hashblu.github.io/hashblu-blog/
  status: true
home_bgfile: bg.jpg
sass:
  sass_dir: assets/css
  style: compressed
markdown: kramdown
kramdown:
  input: GFM
  hard_wrap: false
highlighter: rouge
gems:
- jekyll-paginate
exclude:
- vendor
